apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-backend-config
  namespace: backstage
data:
  app-config.production.yaml: |
    backend:
      reading:
        allow:
          - host: localhost
          - host: backstage.backstage.svc.cluster.local
      baseUrl: http://backstage.backstage.svc.cluster.local:7007
      debug:
        env: true
      cache:
        store: memory
      database:
        client: pg
        connection:
          host: backstage-postgres
          port: 5432
          user: backstage
          password: backstage
      plugins:
        app:
          enabled: false