apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-catalog
  namespace: backstage
data:
  ml-models.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: bert-sentiment-analysis
      title: BERT Sentiment Analysis
      description: A pre-trained BERT model for sentiment analysis
    spec:
      type: ml-model
      lifecycle: production
      owner: guest
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: stable-diffusion
      title: Stable Diffusion
      description: Text-to-image diffusion model
    spec:
      type: ml-model
      lifecycle: production
      owner: guest
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: guest
    spec:
      memberOf: [default-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: default-team
    spec:
      type: team
      children: []