apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-entities
  namespace: backstage
data:
  entities.yaml: |
    # Don't include the Location entity as it's referencing files that don't exist
    # and causing URL parsing errors
    
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: default-team
      description: The Default Team
      namespace: development
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: guest
      namespace: development
    spec:
      # Include the namespace in the memberOf reference
      memberOf: [development/default-team]
    ---
    # Example website
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: example-website
      description: An example website
      namespace: development
    spec:
      type: website
      lifecycle: production
      owner: development/default-team
    ---
    # Example service
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: example-service
      description: An example service
      namespace: development
    spec:
      type: service
      lifecycle: production
      owner: development/default-team
    ---
    # ML Model - BERT
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: bert-sentiment-analysis
      description: A pre-trained BERT model for sentiment analysis
      namespace: development
      annotations:
        backstage.io/source-location: url:https://github.com/google-research/bert
        backstage.io/techdocs-ref: url:https://github.com/google-research/bert
      tags:
        - ml-model
        - transformer
        - nlp
    spec:
      type: service
      lifecycle: production
      owner: development/default-team
    ---
    # ML Model - Stable Diffusion
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: stable-diffusion
      description: Text-to-image diffusion model
      namespace: development
      annotations:
        backstage.io/source-location: url:https://github.com/CompVis/stable-diffusion
        backstage.io/techdocs-ref: url:https://github.com/CompVis/stable-diffusion
      tags:
        - ml-model
        - generative-ai
        - image-generation
    spec:
      type: service
      lifecycle: production
      owner: development/default-team