apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-templates
  namespace: backstage
data:
  templates.yaml: |
    # Only include working external templates
    apiVersion: scaffolder.backstage.io/v1beta3
    kind: Template
    metadata:
      name: nodejs-template
      title: Node.js Service
      description: Create a Node.js service
      tags:
        - recommended
        - node
    spec:
      owner: development/default-team
      type: service
      parameters:
        - title: Fill in service details
          properties:
            name:
              title: Name
              type: string
              description: Unique name of the service
      steps:
        - id: log
          name: Debug Log
          action: debug:log
          input:
            message: Creating service ${{ parameters.name }}