apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  app-config.yaml: |
    catalog:
      rules:
        - allow: [Component, API, Resource, Location, System, Domain, User, Group, Template]
      locations:
        - type: configmap
          target: backstage/backstage-entities
          allow:
            - Group
            - User
            - Component
        # Only include ONE template location
        - type: file
          target: /app/templates/ml-model-template.yaml
          rules:
            - allow: [Template]
    
    # TechDocs configuration (required at root level)
    techdocs:
      builder: local
      generator:
        runIn: docker
      publisher:
        type: local
    
    # Enable events plugin
    events:
      backend:
        enabled: true
    
    # Kubernetes integration
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: ai-platform-cluster
              serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
              url: ${K8S_CLUSTER_URL}
              skipTLSVerify: false
              authProvider: 'serviceAccount'
              skipMetricsLookup: true
    scaffolder:
      log:
        level: debug
      actions:
        enabled: true
      # Enable all default actions
      defaultActions: true
