apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-templates
  namespace: backstage
data:
  templates.yaml: |
    # Use a Location entity to reference an embedded template
    apiVersion: backstage.io/v1alpha1
    kind: Location
    metadata:
      name: ml-templates
      description: Templates for ML models
    spec:
      type: template
      targets:
        - ./ml-model-template.yaml
    ---
    # Embedded template
    apiVersion: scaffolder.backstage.io/v1beta3
    kind: Template
    metadata:
      name: ml-model-template
      title: Hugging Face Model
      description: Deploy a Hugging Face model to Kubernetes with GPU support
      tags:
        - ml
        - gpu
        - kubernetes
    spec:
      owner: development/default-team
      type: service
      parameters:
        - title: Basic Information
          required:
            - name
          properties:
            name:
              title: Name
              type: string
              description: Name for the ML model
      steps:
        - id: debug
          name: Debug Step
          action: debug:log
          input:
            message: Template test successful