apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  app-config.yaml: |
    # Force database reset and reindexing
    catalog:
      database:
        resetOnStartup: true
      processingInterval:
        milliseconds: 10000
      rules:
        - allow: [Component, System, API, Resource, Location, Template, Group, User]
      locations:
        - type: url
          target: https://github.com/re-cinq/meetup-ai/blob/main/backstage/templates/ml-model-template.yaml
          rules:
            - allow: [Template]
        - type: file
          target: /app/examples/entities.yaml
      providers:
        backstageOpenapi:
          plugins:
            - catalog
            - scaffolder
            - permission
        file:
          bootstrap: true
          bootstrapPath: /app/examples
    
    backend:
      baseUrl: http://backstage.backstage.svc.cluster.local:7007
      logging:
        level: debug  # Change to debug for more info
      listen:
        port: 7007
      staticAssets:
        mountPoint: /static
      serve:
        static:
          assets:
            - target: /
              source: /app/packages/app/dist
    
    # Configure scaffolder
    scaffolder:
      frontend:
        filterTemplatesOnUserEntities: false
        templateFilter: false
      log:
        level: info
      actions:
        enabled: true
      defaultActions: true
      registry:
        templates:
          - apiVersion: scaffolder.backstage.io/v1beta3
            kind: Template
            metadata:
              name: direct-ml-model
              title: ML Model Template
              description: Deploy a machine learning model
              tags:
                - recommended
                - ai
                - gpu
            spec:
              owner: development/default-team
              type: service
              parameters:
                - title: Provide Information
                  required:
                    - name
                  properties:
                    name:
                      title: Name
                      type: string
                      description: Unique name for the model
              steps:
                - id: log
                  name: Log
                  action: debug:log
                  input:
                    message: Creating ${{ parameters.name }}
          - apiVersion: scaffolder.backstage.io/v1beta3
            kind: Template
            metadata:
              name: simple-test-template
              title: Test Template
              description: Simple test template
            spec:
              steps:
                - id: log
                  name: Log
                  action: debug:log
                  input:
                    message: "Test message"
    
    app:
      title: AI Platform
      baseUrl: http://backstage.backstage.svc.cluster.local:7007
      frontend:
        debugEnabled: true
        baseUrl: http://backstage.backstage.svc.cluster.local:7007
      packages:
        - name: example-app
          version: 0.2.107
          path: /app/packages/app

    auth:
      environment: development
      providers: 
        guest:
          enabled: true
      keys:
        development:
          skipKeyStoreCheck: true
      allowGuestAccess: true
    
    techdocs:
      builder: local
      generator:
        runIn: docker
      publisher:
        type: local
    
    events:
      backend:
        enabled: true
    
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: ai-platform-cluster
              url: ${K8S_CLUSTER_URL}
              skipTLSVerify: false
              authProvider: 'serviceAccount'
              skipMetricsLookup: true
    
    cache:
      refreshIntervalSeconds: 5

    scorecards:
      enabled: true
      disabled: false
      components:
        default:
          title: Default Components
          description: Default scorecard for components
          filter: kind:component
          cards:
            - title: ML Model Readiness
              type: basic
              description: Checks if the ML model is properly configured
              spec:
                min: 0
                max: 100
                unit: "%"
