apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: ML Platform
      baseUrl: http://backstage.default.svc.cluster.local

    backend:
      baseUrl: http://backstage.default.svc.cluster.local
      listen:
        port: 7007
      database:
        client: better-sqlite3
        connection: ':memory:'
      cache:
        store: memory

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'

    grafana:
      domain: example.com
      isEnabled: false

    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: 'ml-platform'
              url: 'https://kubernetes.default.svc'
              skipTLSVerify: true
              # Use serviceAccount without specifying token - it will be auto-discovered
              authProvider: 'serviceAccount'
              # Note: serviceAccountToken field is removed entirely

    catalog:
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml