apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: ML Platform
      baseUrl: http://backstage.default.svc.cluster.local

    backend:
      baseUrl: http://backstage.default.svc.cluster.local
      listen:
        port: 7007
      database:
        client: better-sqlite3
        connection: ':memory:'
      cache:
        store: memory

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'

    grafana:
      domain: example.com
      isEnabled: false

    # Explicitly set kubernetes config
    kubernetes:
      enabled: false
      clusterLocatorMethods: []

    catalog:
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
  
  # Add a production config file that explicitly disables kubernetes
  app-config.production.yaml: |
    kubernetes:
      enabled: false
      clusterLocatorMethods: []