apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  APP_BASE_URL: "http://backstage-service:3000"
  DATABASE_URL: "postgres://user:password@postgres-service:5432/backstage"
  # Add other configuration values as needed
  # For example, you can specify plugins or other settings here
