apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: ML Platform
      baseUrl: http://backstage.default.svc.cluster.local

    backend:
      baseUrl: http://backstage.default.svc.cluster.local
      listen:
        port: 7007
      database:
        client: better-sqlite3
        connection: ':memory:'
      cache:
        store: memory
      auth:
        # Configure authentication to not require login for demo
        keys:
          - secret: backstage-demo-key
        providers: {}

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'

    grafana:
      domain: example.com
      isEnabled: false

    # Explicitly set kubernetes config
    kubernetes:
      enabled: false
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods: []

    catalog:
      # Set up anonymous access to the catalog
      rules:
        - allow: [read, create, update, delete]
          resources: [catalog-entity]
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/org.yaml
        - type: file
          target: /app/catalog/ml-models.yaml
  
  # Add a more complete production config file
  app-config.production.yaml: |
    app:
      title: ML Platform
    
    backend:
      database:
        client: better-sqlite3
        connection: ':memory:'
    permission:
      enabled: false
    
    auth:
      # Enable guest access for demo purposes
      providers:
        guest:
          enabled: true
          authHandler: 
            allowGuestAccess: true

    # Complete kubernetes configuration to avoid errors
    kubernetes:
      enabled: false
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters: []

    auth:
      # Disable authentication for the demo
      providers: {}
      environment: development