apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: ghcr.io/backstage/backstage:latest
        ports:
        - containerPort: 7007
        env:
        - name: K8S_SERVICE_ACCOUNT_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-k8s-reader-token
              key: token
        - name: K8S_CLUSTER_URL
          value: "https://kubernetes.default.svc.cluster.local"
        - name: NODE_ENV
          value: development
        # Database configuration
        - name: POSTGRES_HOST
          value: "backstage-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_client
          value: "pg"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_host
          value: "backstage-postgres"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_port
          value: "5432"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_user
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_password
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_database
          value: "backstage"
        # Auth configuration
        - name: BACKSTAGE_APP_CONFIG_auth_providers_guest_enabled
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_auth_allowGuestAccess
          value: "true"
        # App configuration
        - name: BACKSTAGE_APP_CONFIG_app_title
          value: "ML Platform"
        # Catalog configuration - SIMPLIFIED
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_type
          value: "file"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_target
          value: "/app/examples/entities.yaml"
        - name: BACKSTAGE_APP_CONFIG_catalog_providers_file_bootstrap
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_catalog_providers_file_bootstrapPath
          value: "/app/examples"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        # Reset database on startup to clear any stale entities
        - name: BACKSTAGE_APP_CONFIG_catalog_database_resetOnStartup
          value: "true"
        # Debug options
        - name: BACKSTAGE_APP_CONFIG_backend_logging_level
          value: "debug"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_type
          value: "file"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_target
          value: "/app/examples/templates.yaml"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: entities
          mountPath: /app/examples/entities.yaml
          subPath: entities.yaml
        - name: templates
          mountPath: /app/examples/templates.yaml
          subPath: templates.yaml
        - name: backstage-k8s-reader-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
        - name: backstage-k8s-reader-token
          secret:
            secretName: backstage-k8s-reader-token
      - name: entities
        configMap:
          name: backstage-entities
      - name: templates
        configMap:
          name: backstage-templates