apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: ghcr.io/backstage/backstage:latest
        ports:
        - containerPort: 7007
        volumeMounts:
        - name: config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
        - name: config 
          mountPath: /app/app-config.production.yaml
          subPath: app-config.production.yaml
        env:
        - name: NODE_ENV
          value: production
        - name: BACKSTAGE_APP_ENV
          value: production
        # Remove PostgreSQL vars and add SQLite vars
        - name: BACKSTAGE_DATABASE_CLIENT
          value: "better-sqlite3"
        - name: BACKSTAGE_DATABASE_CONNECTION
          value: ":memory:"
        - name: BACKSTAGE_KUBERNETES_ENABLED
          value: "false"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: config
        configMap:
          name: backstage-config
      - name: catalog
        configMap:
          name: backstage-catalog