apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage-k8s-reader
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: gchr.io/backstage/backstage:latest
        ports:
        - containerPort: 7007
        env:
        - name: K8S_CLUSTER_URL
          value: "https://kubernetes.default.svc.cluster.local"
        - name: NODE_ENV
          value: development
        - name: POSTGRES_HOST
          value: "backstage-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_client
          value: "pg"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_host
          value: "backstage-postgres"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_port
          value: "5432"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_user
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_password
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_database
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_auth_providers_guest_enabled
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_auth_allowGuestAccess
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_app_title
          value: "ML Platform"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_type
          value: "file"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_target
          value: "/app/examples/entities.yaml"
        - name: BACKSTAGE_APP_CONFIG_catalog_providers_file_bootstrap
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_catalog_providers_file_bootstrapPath
          value: "/app/examples"
        - name: BACKSTAGE_APP_CONFIG_catalog_rules_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_rules_allow_0
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_database_resetOnStartup
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_backend_logging_level
          value: "info"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_type
          value: "url"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_target
          value: "https://github.com/re-cinq/meetup-ai/blob/main/backstage/templates/ml-model-template.yaml"
        - name: BACKSTAGE_APP_CONFIG_auth_environment
          value: "development"
        - name: BACKSTAGE_APP_CONFIG_backend_log_level
          value: "info"
        - name: BACKSTAGE_APP_CONFIG_techdocs_builder
          value: "local"
        - name: BACKSTAGE_APP_CONFIG_techdocs_generator_runIn
          value: "docker"
        - name: BACKSTAGE_APP_CONFIG_techdocs_publisher_type
          value: "local"
        - name: BACKSTAGE_APP_CONFIG_kubernetes_clusterLocatorMethods_0_clusters_0_authProvider
          value: "serviceAccount"
        - name: BACKSTAGE_APP_CONFIG_kubernetes_clusterLocatorMethods_0_clusters_0_skipMetricsLookup
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_catalog_processors_scaffolderTemplateProcessor_enabled
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_scaffolder_defaultActions
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_app_frontend_debugEnabled
          value: "false"
        - name: BACKSTAGE_APP_CONFIG_scaffolder_frontend_filterTemplatesOnUserEntities
          value: "false"
        - name: BACKSTAGE_APP_CONFIG_catalog_processingInterval_milliseconds
          value: "10000"
        - name: BACKSTAGE_APP_CONFIG_scaffolder_log_level
          value: "info"
        - name: BACKSTAGE_APP_CONFIG_catalog_log_level
          value: "info"
        - name: LOG_LEVEL
          value: "info"
        - name: BACKSTAGE_APP_CONFIG_cache_refreshIntervalSeconds
          value: "5"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: entities
          mountPath: /app/examples/entities.yaml
          subPath: entities.yaml
        - name: backstage-app-config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
      volumes:
      - name: entities
        configMap:
          name: backstage-entities
      - name: backstage-app-config
        configMap:
          name: backstage-app-config
