apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: giantswarm/backstage:latest
        ports:
        - containerPort: 7007
        env:
        - name: NODE_ENV
          value: production
        - name: APP_CONFIG_app_baseUrl
          value: "http://localhost:7007"
        - name: APP_CONFIG_backend_baseUrl
          value: "http://localhost:7007"
        volumeMounts:
        - name: app-config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
      volumes:
      - name: app-config
        configMap:
          name: backstage-config