apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: ghcr.io/backstage/backstage:latest
        ports:
        - containerPort: 7007
        env:
        - name: NODE_ENV
          value: development
        # Configure PostgreSQL
        - name: POSTGRES_HOST
          value: "backstage-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_client
          value: "pg"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_host
          value: "backstage-postgres"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_port
          value: "5432"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_user
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_password
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_database
          value: "backstage"
        # Disable Kubernetes plugin
        - name: BACKSTAGE_APP_CONFIG_kubernetes_enabled
          value: "false"
        # Enable guest authentication
        - name: BACKSTAGE_APP_CONFIG_auth_providers_guest_enabled
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_auth_providers_guest_authHandler_allowGuestAccess
          value: "true"
        # Disable permissions
        - name: BACKSTAGE_APP_CONFIG_permission_enabled
          value: "false"
        - name: BACKSTAGE_APP_CONFIG_app_title
          value: "ML Platform"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_type
          value: "url"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_0_target
          value: "https://raw.githubusercontent.com/backstage/backstage/master/packages/catalog-model/examples/all-components.yaml"
        - name: BACKSTAGE_APP_CONFIG_catalog_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_2_type
          value: "url"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_2_target
          value: "https://raw.githubusercontent.com/backstage/backstage/master/packages/catalog-model/examples/acme-corp.yaml"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_type
          value: "file"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_target
          value: "/app/catalog-data/ml-models.yaml"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_1_rules_0_allow
          value: "[Component, System, API, Resource, Location, Template, Group, User]"
        - name: BACKSTAGE_APP_CONFIG_backend_logging_level  
          value: "debug"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_3_type
          value: "file"
        - name: BACKSTAGE_APP_CONFIG_catalog_locations_3_target
          value: "/app/direct/direct-entity.yaml"
        - name: BACKSTAGE_APP_CONFIG_auth_allowGuestAccess
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_backend_auth_keys
          value: "temporary-auth-key"
        - name: BACKSTAGE_APP_CONFIG_backend_auth_allowedHeaders
          value: "authorization,x-requested-with,x-forwarded-user"
        - name: BACKSTAGE_APP_CONFIG_backend_auth_skipDefaultsForPath
          value: "[/api/catalog/locations, /api/catalog/entities]"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: catalog-data
          mountPath: /app/catalog-data
        - name: direct-entity
          mountPath: /app/direct
        - name: additional-examples
          mountPath: /app/examples/entities.yaml
          subPath: entities.yaml
        - name: additional-examples
          mountPath: /app/examples/org.yaml
          subPath: org.yaml
        - name: template-example
          mountPath: /app/examples/template
      volumes:
      - name: catalog-data
        configMap:
          name: backstage-catalog
      - name: direct-entity
        configMap:
          name: direct-entity
      - name: additional-examples
        configMap:
          name: backstage-additional-examples
      - name: template-example
        configMap:
          name: backstage-template-example