apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: backstage/backstage:latest
        ports:
        - containerPort: 7007
        env:
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: backstage-config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
      volumes:
      - name: backstage-config
        configMap:
          name: backstage-config
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"