apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage-k8s-reader
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: europe-west4-docker.pkg.dev/meetup-ai/meetup-ai/backstage-custom:1.1.22
        ports:
        - containerPort: 7007
        env:
        - name: K8S_CLUSTER_URL
          value: "https://kubernetes.default.svc.cluster.local"
        - name: NODE_ENV
          value: development
        - name: POSTGRES_HOST
          value: "backstage-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_client
          value: "pg"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_host
          value: "backstage-postgres"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_port
          value: "5432"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_user
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_password
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_backend_database_connection_database
          value: "backstage"
        - name: BACKSTAGE_APP_CONFIG_auth_providers_guest_enabled
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_auth_allowGuestAccess
          value: "true"
        - name: BACKSTAGE_APP_CONFIG_backend_baseUrl
          value: "http://backstage.backstage.svc.cluster.local:7007"
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
