apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backstage
        image: europe-west4-docker.pkg.dev/meetup-ai/meetup-ai/backstage:latest
        ports:
        - containerPort: 7007
        volumeMounts:
        - name: config
          mountPath: /app/app-config.custom.yaml
          subPath: app-config.yaml
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: config
        configMap:
          name: backstage-config