apiVersion: v1
kind: ConfigMap
metadata:
  name: direct-entity
  namespace: backstage
data:
  direct-entity.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: direct-test-entity
      description: Entity for testing direct loading
    spec:
      type: service
      lifecycle: experimental
      owner: guest