apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-additional-examples
  namespace: backstage
data:
  entities.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: example-website
      description: An example website
    spec:
      type: website
      lifecycle: production
      owner: guest
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: example-service
      description: An example service
    spec:
      type: service
      lifecycle: production
      owner: guest
  
  org.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: guest
    spec:
      memberOf: [default-team]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: default-team
    spec:
      type: team
      children: []