apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-skeleton-template
  namespace: backstage
data:
  "template.yaml": |
    apiVersion: scaffolder.backstage.io/v1beta3
    kind: Template
    metadata:
      name: ml-skeleton
      title: ML Model Skeleton
      description: Create a new ML model deployment
    spec:
      owner: development/default-team
      type: service
      parameters:
        - title: Provide information
          required:
            - component_id
            - owner
          properties:
            component_id:
              title: Name
              type: string
              description: Unique name for the ML model
              ui:field: EntityNamePicker
            owner:
              title: Owner
              type: string
              description: Owner of the component
              ui:field: OwnerPicker
              ui:options:
                allowedKinds:
                  - Group
      steps:
        - id: log
          name: Log
          action: debug:log
          input:
            message: "Creating ML model: ${{ parameters.component_id }}"