apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-k8s-reader
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-k8s-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-k8s-reader
subjects:
  - kind: ServiceAccount
    name: backstage-k8s-reader
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: backstage-k8s-reader
  apiGroup: rbac.authorization.k8s.io