apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 7007
      targetPort: 7007
      protocol: TCP
  selector:
    app: backstage