kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://kubernetes.default.svc.cluster.local
          name: in-cluster
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: true