app:
  title: ML Platform
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:' # Or use a file path for persistence: 'backstage.sqlite3'

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

# grafana:
#   domain: grafana.example.com
#   isEnabled: true

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: 'ml-platform'
          url: 'https://kubernetes.default.svc'
          skipTLSVerify: true # For demo purposes only!
          authProvider: 'serviceAccount'
          serviceAccountToken: "" # For demo purposes only!

catalog:
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
    - type: file
      target: ./catalog-info.yaml