app:
  title: ML Platform
  baseUrl: http://localhost:3000

organization:
  name: RE-CINQ

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  import:
    entityFilename: catalog-info.yaml
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: url
      target: https://github.com/your-username/meetup-ai/blob/master/backstage/catalog-info.yaml

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: gke-cluster
          url: https://kubernetes.default.svc
          authProvider: 'serviceAccount'
          skipTLSVerify: true

scaffolder:
  defaultAuthor:
    name: Backstage
    email: admin@example.com
  defaultCommitMessage: "Created from ML Platform template"

auth:
  environment: development
  providers: {}