apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ml-platform
  description: ML Platform for deploying Hugging Face models
  tags:
    - ml
    - gpu
    - kubernetes
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: data-science
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: huggingface-bert-api
  description: API for accessing the BERT model
spec:
  type: openapi
  lifecycle: experimental
  owner: data-science
  definition: |
    openapi: 3.0.0
    info:
      title: BERT Model API
      version: 1.0.0
      description: API for the BERT model
    paths:
      /predict:
        post:
          summary: Get text embeddings
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    text:
                      type: string
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      embeddings:
                        type: array