apiVersion: v1
kind: Namespace
metadata:
  name: ml-models
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-resources
  namespace: ml-models
spec:
  hard:
    limits.nvidia.com/gpu: "2"
    requests.nvidia.com/gpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: bert-model
  namespace: ml-models
spec:
  selector:
    app: bert-model
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP