apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: huggingface-model-template
  title: Hugging Face Model
  description: Deploy a Hugging Face model to Kubernetes with GPU support
  tags:
    - ml
    - gpu
    - kubernetes
    - recommended
spec:
  owner: development/default-team  # Match your existing team
  type: service

  parameters:
    - title: Provide Information
      required:
        - modelName
        - modelVersion
        - namespace
      properties:
        modelName:
          title: Model Name
          type: string
          description: Name of the Hugging Face model
          ui:field: EntityNamePicker
        modelVersion:
          title: Model Version
          type: string
          description: Version/tag of the model
          default: latest
        namespace:
          title: Kubernetes Namespace
          type: string
          description: Namespace to deploy the model
          default: default
        gpuCount:
          title: GPU Count
          type: number
          description: Number of GPUs to allocate
          default: 1
        replicas:
          title: Replicas
          type: number
          description: Number of replicas
          default: 1

  steps:
    # Start with a simple debug step to ensure it works
    - id: log-start
      name: Log Start
      action: debug:log
      input:
        message: "Starting deployment of ${{ parameters.modelName }} version ${{ parameters.modelVersion }}"

    # Fetch template manifests
    - id: template-k8s-manifest
      name: Create Kubernetes Manifests
      action: fetch:template
      input:
        url: ./manifests
        values:
          modelName: ${{ parameters.modelName }}
          modelVersion: ${{ parameters.modelVersion }}
          namespace: ${{ parameters.namespace }}
          gpuCount: ${{ parameters.gpuCount }}
          replicas: ${{ parameters.replicas }}

    # Publish to Kubernetes
    - id: publish-kubernetes
      name: Publish to Kubernetes
      action: debug:log  # Temporarily use debug:log until kubernetes action is confirmed working
      input:
        message: "Would deploy ${{ parameters.modelName }} to namespace ${{ parameters.namespace }} with ${{ parameters.gpuCount }} GPUs"

  output:
    links:
      - title: Model API
        url: https://${{ parameters.modelName }}.example.com