apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gke-gpu-backstage-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-repo/gke-gpu-backstage-demo
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gke-gpu-backstage-demo
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gke-gpu-backstage-demo
  targetNamespace: default