apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-template-example
  namespace: backstage
data:
  "template.yaml": |
    apiVersion: scaffolder.backstage.io/v1beta3
    kind: Template
    metadata:
      name: example-template
      title: Example Template
      description: An example template
    spec:
      owner: guest
      type: service
      parameters:
        - title: Fill in some steps
          required:
            - name
          properties:
            name:
              title: Name
              type: string
              description: Unique name of the component
              ui:autofocus: true
      steps:
        - id: log
          name: Log
          action: debug:log
          input:
            message: Creating component ${{ parameters.name }}
      output:
        links:
          - title: Open Component
            url: catalog/default/component/${{ parameters.name }}